// tests/helpers/setup.ts
//
// Shared test setup used by both sss-1.ts and sss-2.ts.
// Handles provider creation, program loading, and common constants.

import * as anchor from "@coral-xyz/anchor";
import { Program, AnchorProvider, BN } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
  Connection,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  TOKEN_2022_PROGRAM_ID,
  getAssociatedTokenAddressSync,
  createAssociatedTokenAccountInstruction,
  getAccount,
  createTransferCheckedInstruction,
  addExtraAccountMetasForExecute,
} from "@solana/spl-token";
import { sendAndConfirmTransaction, Transaction } from "@solana/web3.js";
import { assert, expect } from "chai";

// Re-export for convenience in test files
export { assert, expect, BN, Keypair, PublicKey, SystemProgram };
export { TOKEN_2022_PROGRAM_ID };

// ============================================================================
// PROGRAM TYPES
// ============================================================================

// These will be generated by `anchor build` in target/types/
export type SssToken = any;
export type SssTransferHook = any;

// ============================================================================
// PDA SEEDS — must match on-chain constants.rs
// ============================================================================

const STABLECOIN_SEED = Buffer.from("stablecoin");
const ROLES_SEED = Buffer.from("roles");
const BLACKLIST_SEED = Buffer.from("blacklist");
const EXTRA_ACCOUNT_METAS_SEED = Buffer.from("extra-account-metas");

// ============================================================================
// PDA DERIVATION
// ============================================================================

export function findConfigPda(
  mint: PublicKey,
  programId: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [STABLECOIN_SEED, mint.toBuffer()],
    programId
  );
}

export function findRolesPda(
  config: PublicKey,
  programId: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [ROLES_SEED, config.toBuffer()],
    programId
  );
}

export function findBlacklistPda(
  config: PublicKey,
  wallet: PublicKey,
  programId: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [BLACKLIST_SEED, config.toBuffer(), wallet.toBuffer()],
    programId
  );
}

export function findExtraMetaListPda(
  mint: PublicKey,
  hookProgramId: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [EXTRA_ACCOUNT_METAS_SEED, mint.toBuffer()],
    hookProgramId
  );
}

// ============================================================================
// TEST CONTEXT
// ============================================================================

/** Everything a test suite needs. Built by `createTestContext`. */
export interface TestContext {
  provider: AnchorProvider;
  connection: Connection;
  program: Program<SssToken>;
  hookProgram: Program<SssTransferHook>;

  // Keypairs
  authority: Keypair;       // master authority / payer
  mintKeypair: Keypair;     // the Token-2022 mint
  minterA: Keypair;         // minter role
  minterB: Keypair;         // second minter
  burner: Keypair;          // burner role
  pauser: Keypair;          // pauser role
  blacklister: Keypair;     // blacklister role (SSS-2)
  seizer: Keypair;          // seizer role (SSS-2)
  userA: Keypair;           // regular user A
  userB: Keypair;           // regular user B
  unauthorized: Keypair;    // has no roles

  // Derived PDAs
  configPda: PublicKey;
  rolesPda: PublicKey;

  // Token accounts (set after init + ATA creation)
  authorityAta: PublicKey;
  userAAta: PublicKey;
  userBAta: PublicKey;
}

/**
 * Create a full test context with funded keypairs and derived PDAs.
 * Call this in `before()` for each test suite.
 */
export async function createTestContext(): Promise<TestContext> {
  const envProvider = AnchorProvider.env();
  const provider = new AnchorProvider(
    envProvider.connection,
    envProvider.wallet,
    { commitment: "confirmed", preflightCommitment: "confirmed" }
  );
  anchor.setProvider(provider);

  const program = anchor.workspace.SssToken as Program<SssToken>;
  const hookProgram = anchor.workspace.SssTransferHook as Program<SssTransferHook>;

  // Generate all keypairs
  const authority = Keypair.generate();
  const mintKeypair = Keypair.generate();
  const minterA = Keypair.generate();
  const minterB = Keypair.generate();
  const burner = Keypair.generate();
  const pauser = Keypair.generate();
  const blacklister = Keypair.generate();
  const seizer = Keypair.generate();
  const userA = Keypair.generate();
  const userB = Keypair.generate();
  const unauthorized = Keypair.generate();

  // Airdrop SOL to all signers
  const connection = provider.connection;
  const keypairsToFund = [
    authority, minterA, minterB, burner, pauser,
    blacklister, seizer, userA, userB, unauthorized,
  ];

  for (const kp of keypairsToFund) {
    const sig = await connection.requestAirdrop(kp.publicKey, 10 * LAMPORTS_PER_SOL);
    await connection.confirmTransaction(sig);
  }

  // Derive PDAs
  const [configPda] = findConfigPda(mintKeypair.publicKey, program.programId);
  const [rolesPda] = findRolesPda(configPda, program.programId);

  // Derive ATAs (they'll be created during tests)
  const authorityAta = getAssociatedTokenAddressSync(
    mintKeypair.publicKey, authority.publicKey, true, TOKEN_2022_PROGRAM_ID
  );
  const userAAta = getAssociatedTokenAddressSync(
    mintKeypair.publicKey, userA.publicKey, true, TOKEN_2022_PROGRAM_ID
  );
  const userBAta = getAssociatedTokenAddressSync(
    mintKeypair.publicKey, userB.publicKey, true, TOKEN_2022_PROGRAM_ID
  );

  return {
    provider, connection, program, hookProgram,
    authority, mintKeypair,
    minterA, minterB, burner, pauser, blacklister, seizer,
    userA, userB, unauthorized,
    configPda, rolesPda,
    authorityAta, userAAta, userBAta,
  };
}

// ============================================================================
// COMMON OPERATIONS
// ============================================================================

/** Initialize an SSS-1 stablecoin. */
export async function initSSS1(ctx: TestContext, name = "Test USD", symbol = "TUSD"): Promise<void> {
  await ctx.program.methods
    .initialize(name, symbol, "", 6, false, false, false)
    .accounts({
      payer: ctx.authority.publicKey,
      mint: ctx.mintKeypair.publicKey,
      stablecoinConfig: ctx.configPda,
      roleManager: ctx.rolesPda,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([ctx.authority, ctx.mintKeypair])
    .rpc();
}

/** Initialize an SSS-2 stablecoin. */
export async function initSSS2(ctx: TestContext, name = "Compliance USD", symbol = "CUSD"): Promise<void> {
  await ctx.program.methods
    .initialize(name, symbol, "", 6, true, true, false)
    .accounts({
      payer: ctx.authority.publicKey,
      mint: ctx.mintKeypair.publicKey,
      stablecoinConfig: ctx.configPda,
      roleManager: ctx.rolesPda,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([ctx.authority, ctx.mintKeypair])
    .rpc();

  // Initialize hook extra account meta list
  const [extraMetaList] = findExtraMetaListPda(
    ctx.mintKeypair.publicKey,
    ctx.hookProgram.programId
  );

  await ctx.program.methods
    .initHookAccounts()
    .accounts({
      payer: ctx.authority.publicKey,
      stablecoinConfig: ctx.configPda,
      mint: ctx.mintKeypair.publicKey,
      extraAccountMetaList: extraMetaList,
      hookProgram: ctx.hookProgram.programId,
      systemProgram: SystemProgram.programId,
    })
    .signers([ctx.authority])
    .rpc();
}

/** Create an ATA for a user if it doesn't exist, then mint tokens to it. */
export async function mintTo(
  ctx: TestContext,
  recipient: PublicKey,
  amount: number,
  minter?: Keypair
): Promise<string> {
  const signer = minter ?? ctx.authority;
  const ata = getAssociatedTokenAddressSync(
    ctx.mintKeypair.publicKey, recipient, true, TOKEN_2022_PROGRAM_ID
  );

  // Create ATA if needed
  const ataInfo = await ctx.connection.getAccountInfo(ata);
  const preIxs = ataInfo
    ? []
    : [createAssociatedTokenAccountInstruction(
        signer.publicKey, ata, recipient,
        ctx.mintKeypair.publicKey, TOKEN_2022_PROGRAM_ID,
      )];

  const sig = await ctx.program.methods
    .mintTokens(new BN(amount))
    .accounts({
      authority: signer.publicKey,
      stablecoinConfig: ctx.configPda,
      roleManager: ctx.rolesPda,
      mint: ctx.mintKeypair.publicKey,
      recipientTokenAccount: ata,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
    })
    .preInstructions(preIxs)
    .signers([signer])
    .rpc();

  await ctx.connection.confirmTransaction(sig, "confirmed");
  return sig;
}

/** Get token balance for a wallet's ATA. */
export async function getBalance(ctx: TestContext, owner: PublicKey): Promise<bigint> {
  const ata = getAssociatedTokenAddressSync(
    ctx.mintKeypair.publicKey, owner, true, TOKEN_2022_PROGRAM_ID
  );
  try {
    const account = await getAccount(ctx.connection, ata, "confirmed", TOKEN_2022_PROGRAM_ID);
    return account.amount;
  } catch {
    return BigInt(0);
  }
}

/**
 * Execute a Token-2022 transfer_checked on an SSS-2 mint with transfer-hook
 * metas resolved from the on-chain ExtraAccountMetaList.
 */
export async function transferWithHook(
  ctx: TestContext,
  sourceTokenAccount: PublicKey,
  destTokenAccount: PublicKey,
  owner: Keypair,
  amount: number,
  decimals: number
): Promise<void> {
  const ix = createTransferCheckedInstruction(
    sourceTokenAccount,
    ctx.mintKeypair.publicKey,
    destTokenAccount,
    owner.publicKey,
    amount,
    decimals,
    [],
    TOKEN_2022_PROGRAM_ID
  );

  await addExtraAccountMetasForExecute(
    ctx.connection,
    ix,
    ctx.hookProgram.programId,
    sourceTokenAccount,
    ctx.mintKeypair.publicKey,
    destTokenAccount,
    owner.publicKey,
    BigInt(amount),
    "confirmed"
  );

  const tx = new Transaction().add(ix);
  await sendAndConfirmTransaction(ctx.connection, tx, [owner], {
    commitment: "confirmed",
  });
}

/** Helper to expect a transaction to fail with a specific error code. */
export async function expectError(
  fn: () => Promise<any>,
  errorCode: string
): Promise<void> {
  try {
    await fn();
    assert.fail("Expected transaction to fail");
  } catch (err: any) {
    const errStr = JSON.stringify(err);
    assert.include(errStr, errorCode, `Expected error ${errorCode} but got: ${err.message}`);
  }
}
